/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import ckeditor from "@ckeditor/strapi-plugin-ckeditor/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import seo from "@strapi/plugin-seo/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import slug from "custom-slug/strapi-admin";
import importExportEntries from "strapi-plugin-import-export-entries/strapi-admin";
import menus from "strapi-plugin-menus/strapi-admin";
import multiSelect from "strapi-plugin-multi-select/strapi-admin";
import navigation from "strapi-plugin-navigation/strapi-admin";
import restCache from "strapi-plugin-rest-cache/strapi-admin";
import sitemap from "strapi-plugin-sitemap/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    ckeditor: ckeditor,
    "strapi-cloud": strapiCloud,
    i18n: i18N,
    seo: seo,
    "users-permissions": usersPermissions,
    slug: slug,
    "import-export-entries": importExportEntries,
    menus: menus,
    "multi-select": multiSelect,
    navigation: navigation,
    "rest-cache": restCache,
    sitemap: sitemap,
  },
});
